### ISSUE TITLE
Ven Stock Revamp Compatibility

### ISSUE THREAD

**Issue by ragzilla** [sumghai/SDHI_ServiceModuleSystem#120]
Ven Stock Revamp breaks the SDHI docking ring, due to the new models including a docking bumper.  Inlined MM patch seems to fix it (by adding the required animation and context menu items).

`@PART[SDHI_ParaDock_1_ClampOTron]:NEEDS[VenStockRevamp]
{
    MODULE
    {
        name = ModuleAnimateGeneric
        animationName = DockingPort_bumper
        isOneShot = false
        startEventGUIName = Deploy bumper
        endEventGUIName = Retract bumper
    }
}`

**Comment by ragzilla** [comment]
Apologies for lack of formatting, github seems to be eating the newlines, and I'm too lazy to do a clone/patch/pull tonight

**Comment by sumghai** [comment]
@ragzilla, sorry for the late response!

I'll test the proposed patch out this weekend, and prep this for the next update in line with KSP 1.3.

Thanks!

**Comment by sumghai** [comment]
@ragzilla, the patch you provided did not add the bumper animation to the SDHI Clamp-O-Tron.

Another observation is that Ven's Clamp-O-Tron model is much, much bigger than the SDHI parachute casing, which makes the resulting (broken) part virtually identical to Ven's own parachute-equipped docking port. So unless Ven can break his/her model down to remove the big casing, there's not much point in supporting the mod.

**Comment by sumghai** [comment]
@ragzilla, the patch _functionally_ works.

However, I found that Ven's revamped docking port model is much bigger than the original stock version, and so it completely encloses the . Furthermore, the Ven revamp model's casings do not blow away when parachutes are being deployed, resulting in the parachutes appearing to emerge from solid metal.

I considered replacing my parachute casing for the SDHI docking port with the one from Ven's parachute-equipped Mk16-XXL model, which does blow away during parachute deployment. However, the Mk16-XXL is thinner than the standard Ven Clamp-O-Tron, which means that the SDHI Mk1-2 BPC would sit lower on the stack than usual, and therefore clip into the Service Module / Avionics Ring under the pod (although a MM patch that shifts the inner attach node on the BPC only when Ven's Revamp is installed is potentially doable).

But the biggest problem I see is redundancy. A user now has both the Ven Mk16-XXL and the SHDI docking port, which are visually identically for the aforementioned reason. Keeping both in the parts list would cause confusion, but using MM patches to hide one or the other parts could result in savebreaking when either Ven's or SDHI is uninstalled.

Thoughts?

**Comment by sumghai** [comment]
I spoke with Ven, and he advised me that making SDHI compatible with his Stock Parts Revamp is not worth my time.

He suggested SDHI should continue to use the old stock Clamp-O-Tron model, while leaving his revamped port untouched.

**Comment by sumghai** [comment]
Nullification patch tested OK, ready for release.
