### ISSUE TITLE
V2.5 dependency checking for KSP 1.0

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#37]
With the recent update of the stock KSP game to 1.0, a number of dependencies need to be checked for compatibility.

Since I currently don't have access to a laptop capable of running the game, I'll need to get volunteers to do this testing for me :P

**Comment by Surplus91** [comment]
What needs to happen? :)

**Comment by steampilot** [comment]
What kind of tests would you need to be performed? If i get some kind of black box test list i could perform them for you.

**Comment by sumghai** [comment]
Right now I'm waiting for a couple of dependencies and a few other optional add-ons to be updated, as well as doing some 1.0-specific aero tweaks in the meantime. 

I'll get back to you guys on this one.

**Comment by steampilot** [comment]
Considereing dependencies: I recomend usind standard decuppler module. 
As i edited your avionics ring to use standard decupler module. The animated decupler never worked for me. Also propably wont be developed further.

**Comment by sumghai** [comment]
The AnimatedDecoupler plugin has worked for the vast majority of users, and @Starwaster has stated he will continue to maintain it. 

Besides, it's the only way to animate the side umbilical, and I'm not sacrificing the latter feature.

**Comment by steampilot** [comment]
Good news then. looking forward to it.

**Comment by Surplus91** [comment]
I only found soms problems with atachment points, for example: the docking ports and heatshield. I have not jet checked the animations :s

**Comment by steampilot** [comment]
nodes can be specified in size. that could help if we set those nodes smaller and the same size for the avionics ring and the heat shield.  i will try that tonight

**Comment by sumghai** [comment]
I'm going to have to ask you guys to hold off on doing any testing on your own. 

The are some serious issues regarding stock aero compatibility, and most folks are coordinating further actions in the SDHI SMS thread on the forums.

**Comment by sumghai** [comment]
Okay guys, thanks for your patience. Please refer to the following test procedures:

https://github.com/sumghai/SDHI_ServiceModuleSystem/wiki/Test-Procedures-for-upcoming-V3.0-release

**Comment by sumghai** [comment]
Reports received so far have been essentially positive. I think this is ready for prime time (barring the decoupler FX fixes).
