### ISSUE TITLE
Mass/strength/cost of adapter awfully high

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [sumghai/SDHI_ServiceModuleSystem#59]
Comparing the adapter to the Rockomax short adapter, the mass, cost, and breaking strengths of the service module adapter are way high (by an order of magnitude or so).  Is this intentional?

**Comment by sumghai** [comment]
Apologies for the late reply.

I can't remember off the top of my head why I picked those values in the first place, or which stock part I derived its specifications from. As such, I'm willing to consider revised values.

If you could make another pull request with your proposed changes, we can look into this further.

**Comment by sumghai** [comment]
Merged Pull Request #58.
