### ISSUE TITLE
Parts don't work in KSP 1.04

### ISSUE THREAD

**Issue by tuthmosis** [sumghai/SDHI_ServiceModuleSystem#60]
The heat shield is just another regular shield and doesn't offer any inflating stuff.
The service module doesn't release the MK1-2 pod. It's options doesn't contain any "Decouple" item and when used in VAB it doesn't generate any staging step.

**Comment by tuthmosis** [comment]
Nevermind.... must be some dependency that were missing.

**Comment by sumghai** [comment]
The inflatable floatation collar is dependent on the Klockheed Martian Special Parts plugin, which unfortunately is no longer being maintained. I haven't been able to find a replacement plugin to support the aforementioned feature, either.

As you probably realised, the Service Module requires @Starwaster's AnimatedDecouplers plugin, which was listed quite clearly as a dependency in the forum threads and README.
