### ISSUE TITLE
ParaDocks missing staging icon in KSP 1.0.5

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#65]
While testing SDHI SMS 3.0.1 on a stock install with minimal dependencies (AnimatedDecouplers, RealChutes and MM), it was noted that the staging icon for the parachute-equipped docking ports are no longer visible.

Parachute deployment, docking and toggleable lights still function normally.

**Comment by sumghai** [comment]
Current workaround is for the user to manually enable staging for the docking port via the right-click context menu. I've asked @NathanKell to see if there is some way of making this permanent.

**Comment by Kerbas-ad-astra** [comment]
From another part config (e.g. [this one](https://github.com/charfa/XTLandertron/blob/master/GameData/Landertron/Parts/XT-L2B/XT-L2B.cfg)), it looks like "stagingEnabled = true" will put the staging icon back.  "staging = true/false" looks like it will enable and disable the *option* to toggle staging, respectively.

**Comment by sumghai** [comment]
No joy.

**staging = false** *does* remove the option to toggle staging, but **stagingEnabled = true** doesn't make the docking ports stageable by default.

I tried this on a clean install with stock parts only, and modified the stock Clamp-o-Tron as above, to no avail.

**Comment by sumghai** [comment]
Might require changes to RealChute, as per StupidChris/RealChute/issues/58.

**Comment by StupidChris** [comment]
RealChute has been updated, new binaries contain the fix.

**Comment by sumghai** [comment]
Tested latest update, confirmed fix works.

Closing.
