### ISSUE TITLE
Contract for testing complete SDHI SMS stack

### ISSUE THREAD

**Issue by sumghai** [sumghai/SDHI_ServiceModuleSystem#81]
To my knowledge, the current version of KSP automatically generates parts testing contracts for mod parts.

Since the SDHI SMS is meant to be used as part of a complete CSM stack, it would be nice to:
- Disable individual part testing contracts
- Create a comprehensive contract to build and test a complete CSM stack
- Additional contracts (e.g. suborbital, LKO, Munar transfer orbit)

**Comment by Kerbas-ad-astra** [comment]
You could disable the stock test contract for your parts (not sure if you'd do that by omitting ModuleTestSubject or by including it with the appropriate options) and include a contract for [**Contract Configurator**](https://github.com/jrossignol/ContractConfigurator/) that requires the appropriate numbers of parts to be present on the same craft.  I don't think there's a way for Contract Configurator to enforce a particular order on the parts, so users could hypothetically assemble everything in some bizarre way, but they'll probably find the conventional method the easiest.  Requiring suborbital, LKO, and Mun/Minmus orbital testing missions in that order is straightforward with CC.

**Comment by sumghai** [comment]
After consulting with @NathanKell, it seems that simply omitting `ModuleTestSubject` automatically prevents the parts from showing up in part test contracts.

As for custom flight test contracts using Contract Configurator, I'll put this on the back burner for now.

**Comment by sumghai** [comment]
I'm scrapping this entirely.
